modify to be quote

diff --git a/git-diff-logs b/git-diff-logs
--- a/git-diff-logs
+++ b/git-diff-logs
@@ -7,7 +7,7 @@ diffopt=();
 while [ "$1" != "" ];do
     if [ "$1" = "-ww" ];then diffopt=(${diffopt[@]} '-w')
     elif [ "$1" = "--from" ];then from=$2;shift
-    elif ! git log -1 "$1" 1>/dev/null 2>&1;then echo 'invalid arg '$1;exit 1
+    elif ! git log -1 "$1" 1>/dev/null 2>&1;then echo 'invalid arg '"$1";exit 1
     elif [ "${1:0:1}" = "-" ];then opt=(${opt[@]} "$1")
     elif [ "$hash1" = "" ];then hash1=$1
     elif [ "$hash2" = "" ];then hash2=$1
@@ -17,4 +17,4 @@ done
 
 if [ "$hash1" = "" ];then echo 'no arg set';exit 1;fi
 
-diff -a $diffopt <(git log -p $from..$hash1 "${opt[@]}") <(git log -p $from..$hash2 "${opt[@]}")
+diff -a $diffopt <(git log -p "$from..$hash1" "${opt[@]}") <(git log -p "$from..$hash2" "${opt[@]}")
