modify gldiff to allow diff without spaces

diff --git a/gldiff b/gldiff
--- a/gldiff
+++ b/gldiff
@@ -2,8 +2,10 @@
 
 eflag=0
 opt=();
+diffopt=();
 while [ "$1" != "" ];do
-    if ! git log -1 $1 1>/dev/null 2>&1;then exit
+    if [ "$1" = "-ww" ];then diffopt=(${diffopt[@]} '-w')
+    elif ! git log -1 $1 1>/dev/null 2>&1;then echo 'invalid arg '$1;exit 1
     elif [ "${1:0:1}" = "-" ];then opt=(${opt[@]} $1)
     elif [ "$hash1" = "" ];then hash1=$1
     elif [ "$hash2" = "" ];then hash2=$1
@@ -13,4 +15,4 @@ done
 
 if [ "$hash1" = "" ];then echo 'no arg set';exit 1;fi
 
-diff -a <(git log -p origin..$hash1 --pretty='format:%C(auto)%h %s%n' "${opt[@]}") <(git log -p origin..$hash2 --pretty='format:%C(auto)%h %s%n' "${opt[@]}")
+diff -a $diffopt <(git log -p origin..$hash1 --pretty='format:%C(auto)%h %s%n' "${opt[@]}") <(git log -p origin..$hash2 --pretty='format:%C(auto)%h %s%n' "${opt[@]}")
